version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    depends_on:
      - db

  home-service:
    build: ./home-service
    ports:
      - "5001:5001"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
